import {
  AlertTriangle,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BarChart2,
  Bell,
  Building2,
  Check,
  ChevronRight,
  Clock,
  Command,
  CreditCard,
  Dot,
  Filter,
  Flag,
  Flame,
  GripVertical,
  Home,
  Layers,
  Link,
  Lock,
  LockOpen,
  Moon,
  Pause,
  Percent,
  Plus,
  RefreshCw,
  Repeat,
  Scale,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  TrendingUp,
  Wallet,
  X,
  type LucideIcon,
} from "lucide-react";
import { LedgerGlyph, type GlyphProps } from "./glyphs/LedgerGlyph";
import type { ComponentType } from "react";

export const UICON_KEYS = [
  "today",
  "ledger",
  "wallet",
  "plan",
  "look",
  "search",
  "plus",
  "up",
  "down",
  "swap",
  "check",
  "flame",
  "alert",
  "repeat",
  "bell",
  "sync",
  "gear",
  "card",
  "flag",
  "trend",
  "sun",
  "moon",
  "dot",
  "x",
  "chevron",
  "drag",
  "clock",
  "home",
  "percent",
  "link",
  "tag",
  "pause",
  "shield",
  "filter",
  "arrowR",
  "scale",
  "command",
  "building",
  "lock",
  "unlock",
  "sliders",
  "sparkle",
  "bnpl",
] as const;

export type UIconKey = (typeof UICON_KEYS)[number];

// Custom glyphs have a compatible-enough prop shape. We cast to LucideIcon
// so the registry stays uniform; the UIcon wrapper only uses the shared props.
type AnyIconComponent = LucideIcon | ComponentType<GlyphProps>;

export const ICON_REGISTRY: Record<UIconKey, AnyIconComponent> = {
  today: Sun, // the "today" room uses the sun glyph (distinct key from `sun`)
  ledger: LedgerGlyph,
  wallet: Wallet,
  plan: Layers,
  look: BarChart2,
  search: Search,
  plus: Plus,
  up: ArrowUp,
  down: ArrowDown,
  swap: ArrowLeftRight,
  check: Check,
  flame: Flame,
  alert: AlertTriangle,
  repeat: Repeat,
  bell: Bell,
  sync: RefreshCw,
  gear: Settings,
  card: CreditCard,
  flag: Flag,
  trend: TrendingUp,
  sun: Sun,
  moon: Moon,
  dot: Dot,
  x: X,
  chevron: ChevronRight,
  drag: GripVertical,
  clock: Clock,
  home: Home,
  percent: Percent,
  link: Link,
  tag: Tag,
  pause: Pause,
  shield: Shield,
  filter: Filter,
  arrowR: ArrowRight,
  scale: Scale,
  command: Command,
  building: Building2,
  lock: Lock,
  unlock: LockOpen,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  bnpl: ShoppingBag,
} satisfies Record<UIconKey, AnyIconComponent>;
